# Generated by Django 5.1.3 on 2025-01-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evos_app', '0001_initial'),
    ]

    operations = [
    ]
