# Generated by Django 5.1.3 on 2024-12-27 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evos_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Ovqat', 'verbose_name_plural': 'Ovqatlar'},
        ),
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='koment matni')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name="qo'shilgan vaqti")),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evos_app.dish', verbose_name='Ovqat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'komentariya',
                'verbose_name_plural': 'komentariyalar',
                'ordering': ['-created'],
            },
        ),
    ]
